In [1]:
# 1. Pandas kurulumu ve sürüm kontrolü

import pandas as pd

print("Pandas sürümü:", pd.__version__)

Pandas sürümü: 3.0.5

In [2]:
# 2. Series oluşturma

sayilar = pd.Series([100, 200, 300, 400])
print(sayilar)

nufus = pd.Series(
    [16000000, 5800000, 5400000, 2500000],
    index=["İstanbul", "Ankara", "İzmir", "Bursa"]
)

print("\nŞehir nüfusları:")
display(nufus)

print("İstanbul nüfusu:", nufus["İstanbul"])
print("Toplam nüfus:", nufus.sum())

0    100
1    200
2    300
3    400
dtype: int64

Şehir nüfusları:

İstanbul    16000000
Ankara       5800000
İzmir        5400000
Bursa        2500000
dtype: int64

İstanbul nüfusu: 16000000
Toplam nüfus: 29700000

In [13]:
# 3. DataFrame oluşturma

urunler = pd.DataFrame({
    "ürün": ["Laptop", "Telefon", "Tablet", "Kulaklık", "Mouse"],
    "fiyat": [30000, 20000, 12000, 2500, 1000],
    "stok": [10, 15, 8, 25, 40]
})

display(urunler)

ogrenciler = pd.DataFrame({
    "isim": ["Ayşe", "Mehmet", "Zeynep", "Ali", "Sena"],
    "yas": [20, 21, 19, 22, 25],
    "bolum": [
        "Bilgisayar Mühendisliği",
        "Yazılım Mühendisliği",
        "Bilgisayar Mühendisliği",
        "Elektrik Elektronik Mühendisliği",
        "Bilgisayar Mühendisliği"
    ]
})

display(ogrenciler)

print("Satır ve sütun sayısı:", ogrenciler.shape)

       ürün  fiyat  stok
0    Laptop  30000    10
1   Telefon  20000    15
2    Tablet  12000     8
3  Kulaklık   2500    25
4     Mouse   1000    40

     isim  yas                             bolum
0    Ayşe   20           Bilgisayar Mühendisliği
1  Mehmet   21              Yazılım Mühendisliği
2  Zeynep   19           Bilgisayar Mühendisliği
3     Ali   22  Elektrik Elektronik Mühendisliği
4    Sena   25           Bilgisayar Mühendisliği

Satır ve sütun sayısı: (5, 3)

In [14]:
# 4. CSV dosyası okuma ve yazma

ogrenciler.to_csv("ogrenciler.csv")

veri = pd.read_csv("ogrenciler.csv")
display(veri)

ogrenciler.to_csv("ogrenciler_indexsiz.csv", index=False)

veri2 = pd.read_csv("ogrenciler_indexsiz.csv")
display(veri2)

   Unnamed: 0    isim  yas                             bolum
0           0    Ayşe   20           Bilgisayar Mühendisliği
1           1  Mehmet   21              Yazılım Mühendisliği
2           2  Zeynep   19           Bilgisayar Mühendisliği
3           3     Ali   22  Elektrik Elektronik Mühendisliği
4           4    Sena   25           Bilgisayar Mühendisliği

     isim  yas                             bolum
0    Ayşe   20           Bilgisayar Mühendisliği
1  Mehmet   21              Yazılım Mühendisliği
2  Zeynep   19           Bilgisayar Mühendisliği
3     Ali   22  Elektrik Elektronik Mühendisliği
4    Sena   25           Bilgisayar Mühendisliği

In [15]:
# 5. DataFrame'i inceleme

display(ogrenciler.head(3))
display(ogrenciler.tail(2))

print("Boyut:", ogrenciler.shape)

ogrenciler.info()

display(ogrenciler["yas"].describe())

print("Yaş ortalaması:", ogrenciler["yas"].mean())
print("Minimum yaş:", ogrenciler["yas"].min())
print("Maksimum yaş:", ogrenciler["yas"].max())

     isim  yas                    bolum
0    Ayşe   20  Bilgisayar Mühendisliği
1  Mehmet   21     Yazılım Mühendisliği
2  Zeynep   19  Bilgisayar Mühendisliği

   isim  yas                             bolum
3   Ali   22  Elektrik Elektronik Mühendisliği
4  Sena   25           Bilgisayar Mühendisliği

Boyut: (5, 3)
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   isim    5 non-null      str
 1   yas     5 non-null      int64
 2   bolum   5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

count     5.000000
mean     21.400000
std       2.302173
min      19.000000
25%      20.000000
50%      21.000000
75%      22.000000
max      25.000000
Name: yas, dtype: float64

Yaş ortalaması: 21.4
Minimum yaş: 19
Maksimum yaş: 25

In [16]:
# 6. Sütun ve satır seçme

display(ogrenciler["isim"])

display(ogrenciler[["isim", "yas"]])

display(ogrenciler.loc[0:2])

print("2. satır ve 2. sütunun kesişimi:", ogrenciler.iloc[1, 1])

0      Ayşe
1    Mehmet
2    Zeynep
3       Ali
4      Sena
Name: isim, dtype: str

     isim  yas
0    Ayşe   20
1  Mehmet   21
2  Zeynep   19
3     Ali   22
4    Sena   25

     isim  yas                    bolum
0    Ayşe   20  Bilgisayar Mühendisliği
1  Mehmet   21     Yazılım Mühendisliği
2  Zeynep   19  Bilgisayar Mühendisliği

2. satır ve 2. sütunun kesişimi: 21

In [11]:
# 7. Koşullu filtreleme

calisanlar = pd.DataFrame({
    "isim": ["Ayşe", "Mehmet", "Zeynep", "Ali", "Sena"],
    "yas": [20, 27, 32, 24, 25],
    "maas": [18000, 25000, 32000, 28000, 40000],
    "sehir": ["İstanbul", "Ankara", "İstanbul", "İzmir", "İstanbul"]
})

display(calisanlar)

display(calisanlar[calisanlar["yas"] > 25])

display(calisanlar[
    (calisanlar["maas"] >= 20000) &
    (calisanlar["maas"] <= 30000)
])

display(calisanlar[calisanlar["sehir"] == "İstanbul"])

display(calisanlar[
    (calisanlar["yas"] < 20) |
    (calisanlar["yas"] > 40)
])

     isim  yas   maas     sehir
0    Ayşe   20  18000  İstanbul
1  Mehmet   27  25000    Ankara
2  Zeynep   32  32000  İstanbul
3     Ali   24  28000     İzmir
4    Sena   25  40000  İstanbul

     isim  yas   maas     sehir
1  Mehmet   27  25000    Ankara
2  Zeynep   32  32000  İstanbul

     isim  yas   maas   sehir
1  Mehmet   27  25000  Ankara
3     Ali   24  28000   İzmir

     isim  yas   maas     sehir
0    Ayşe   20  18000  İstanbul
2  Zeynep   32  32000  İstanbul
4    Sena   25  40000  İstanbul

Empty DataFrame
Columns: [isim, yas, maas, sehir]
Index: []

In [8]:
# 8. Yeni sütun ekleme ve değer güncelleme

calisanlar["dogum_yili"] = 2026 - calisanlar["yas"]

calisanlar["maas"] = calisanlar["maas"] * 1.10

calisanlar["durum"] = calisanlar["yas"].apply(
    lambda x: "Yetişkin" if x > 18 else "Çocuk"
)

display(calisanlar)

     isim  yas     maas     sehir  dogum_yili     durum
0    Ayşe   20  19800.0  İstanbul        2006  Yetişkin
1  Mehmet   27  27500.0    Ankara        1999  Yetişkin
2  Zeynep   32  35200.0  İstanbul        1994  Yetişkin
3     Ali   24  30800.0     İzmir        2002  Yetişkin
4    Sena   41  44000.0  İstanbul        1985  Yetişkin

In [12]:
# 9. Sıralama işlemleri

display(calisanlar.sort_values("yas"))

display(calisanlar.sort_values("maas", ascending=False))

display(calisanlar.sort_values(["sehir", "yas"]))

     isim  yas   maas     sehir
0    Ayşe   20  18000  İstanbul
3     Ali   24  28000     İzmir
4    Sena   25  40000  İstanbul
1  Mehmet   27  25000    Ankara
2  Zeynep   32  32000  İstanbul

     isim  yas   maas     sehir
4    Sena   25  40000  İstanbul
2  Zeynep   32  32000  İstanbul
3     Ali   24  28000     İzmir
1  Mehmet   27  25000    Ankara
0    Ayşe   20  18000  İstanbul

     isim  yas   maas     sehir
1  Mehmet   27  25000    Ankara
0    Ayşe   20  18000  İstanbul
4    Sena   25  40000  İstanbul
2  Zeynep   32  32000  İstanbul
3     Ali   24  28000     İzmir